# Generated by Django 4.1.7 on 2023-04-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=None)),
                ('humidity', models.FloatField(default=None)),
                ('meas_date', models.DateTimeField(verbose_name='date measured')),
            ],
        ),
    ]
